### ISSUE TITLE
Make GitHub OAuth more secure with jwt

### ISSUE THREAD

**Issue by VulcanWM** [VulcanWM/guest-book#22]

**Comment by Shreyas-SAS** [comment]
Hey! want me to do this as an open-source contribution? I can do it for free, no worries. It's really simple. Just a few lines.

**Comment by VulcanWM** [comment]
Yeah that would be great if you could!

**Comment by Shreyas-SAS** [comment]
sorry, it will take a bit more time. There is a conflict with my code since I didn't create a new branch the last time I edited it. Will do the job in next 10 minutes or so.

**Comment by Shreyas-SAS** [comment]
hey @VulcanWM you have the .env file configured right? then I would not create it. It might undo your work. I will tell you what to do please follow that at your end.

**Comment by Shreyas-SAS** [comment]
My PR is just 1 line changed but please follow the instructions that I am sending here.

**Comment by Shreyas-SAS** [comment]
Please follow these steps to generate a JSON Web Token for your account:
Step 11: run the command "openssl rand -base64 32" on the terminal. If it does not work visit the website https://generate-secret.vercel.app/32
Step 12: copy the code generated and paste it in front of JWT_SECRET=
Step 13: you are now done with configuring the Github authentication with additional JWT based Auth Security.

**Comment by Shreyas-SAS** [comment]
> 12: copy the code generated and paste it in front of JWT_SECRET= 
For this line the code would not be there. In order to add JWT we need to add another line as 
`JWT_SECRET=generated code here` 
to the .env file.

**Comment by VulcanWM** [comment]
hey is the pull request up to date with this repo?

**Comment by VulcanWM** [comment]
added the secure line
