### ISSUE TITLE
Proposal: Add README for the project

### ISSUE THREAD

**Issue by Shreyas-SAS** [VulcanWM/guest-book#29]
Hey @VulcanWM, I was wondering If you would be interested in me creating documentation for this project. I saw that it was missing so maybe I can contribute to it. I will be applying for GSoD this year so will be a good practice.

**Comment by VulcanWM** [comment]
yea sure

**Comment by Shreyas-SAS** [comment]
Currently my exams are on so can I work on it after 1st may?

**Comment by VulcanWM** [comment]
definitely! that's when ill start reworking on this project too!

**Comment by VulcanWM** [comment]
just created the readme file and a simple message, feel free to add whatever you want to it

**Comment by Shreyas-SAS** [comment]
@VulcanWM I will work on it today and will most likely make a PR by EOD. please give me feedback then. Thanks.

**Comment by VulcanWM** [comment]
sure, thanks!

**Comment by VulcanWM** [comment]
thanks for your help!
