### ISSUE TITLE
Proposal: Add a Directory Flow for Contributors

### ISSUE THREAD

**Issue by Shreyas-SAS** [VulcanWM/guest-book#39]
Hey @VulcanWM, I was wondering if I could work on creating a new file as contributing.md that would enlist places to look for when contributing to the project for more accessible contributions. It would take time though, since I have 3 other issues assigned at other orgs and will complete them first.
If this is ok with you, please assign me the issue, and I will complete it afterward.

**Comment by VulcanWM** [comment]
Hey, I don't really need anyone to contribute to this repo, as I'm happy with all the features and don't need anymore. 
However, I do have two projects: [GitHub Actions MongoDB(https://github.com/VulcanWM/github-actions-mongodb) and [Global CSS Art](https://github.com/VulcanWM/global-css-art) which do require a better contributing.md file. So feel free to work on them if you want.
